### ISSUE TITLE
Script never end

### ISSUE THREAD

**Issue by Lecraver** [dypa/phpmulticurl#4]
Hi,
Is it working with PHP7.3.10 and cURL 7.58 ?
the script runs smoothly up to $phpMultiCurl->executeTasks($queue); where an infinite loop seems to be launched.
Any idea ?
many thanks

**Comment by dypa** [comment]
>Is it working with PHP7.3.10 and cURL 7.58 ?
no, \curl_multi_select in php 7 works different to php5. i will fix this error in feature release as soon as possible

**Comment by dypa** [comment]
shold be fixed in `4.0.0`, but i strongly recomend you to look at `guzzle/guzzle` and their CurlMultiHandler as alternative.
